version: 2
jobs:
  build:
    docker:
      - image: thinkshout/nginx-php-fpm:php74
        environment:
          WEBROOT: /var/www/html/drupal-project/web
          GIT_EMAIL: "ci@thinkshout.com"
          GIT_NAME: "ThinkShout CI Bot"
          IS_CIRCLE: TRUE
        command: [ "/start.sh" ]
      - image: mariadb:10.4
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: 1
          MYSQL_DATABASE: circletest
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
    working_directory: /var/www/html/drupal-project
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Test site install works
          command: |
            echo "memory_limit = 512M"  >> ${php_vars}
            export PATH="./vendor/bin:../vendor/bin:/root/.composer/vendor/bin:$PATH"
            composer self-update --2
            COMPOSER_MEMORY_LIMIT=-1 composer create-project wri/wri-starter-kit:dev-main circletest
            cd circletest
            COMPOSER_MEMORY_LIMIT=-1 composer require wri/wri_sites:dev-${CIRCLE_BRANCH} --update-with-dependencies
            drush si wri_sites -y --verbose --db-url=mysql://drupal:drupal@127.0.0.1:3306/circletest
  test:
    docker:
      - image: thinkshout/nginx-php-fpm:php74
        environment:
          WEBROOT: /var/www/html/drupal-project/web
          GIT_EMAIL: "ci@thinkshout.com"
          GIT_NAME: "ThinkShout CI Bot"
          IS_CIRCLE: TRUE
        command: [ "/start.sh" ]
    working_directory: /var/www/html/drupal-project
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Run CS tests
          command: |
            export PATH="./vendor/bin:../vendor/bin:/root/.composer/vendor/bin:$PATH"
            composer self-update --2
            COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist
            phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info,txt,md,profile --ignore="*.css,*/node_modules/*,*/dist/*,README.md,web/*,*.js" modules themes wri_sites.install wri_sites.profile
            rm -r web
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test