block.settings.wri_topics_wrin_topics:
  type: block_settings
  label: 'WRIN Topics block'
  mapping:
    topic_intro_text:
      type: text
      label: Intro Text
    hide_centers:
      type: boolean
      label: Hide Centers
